from . import model_a
from . import model_b
from . import model_c
from . import model_d
from . import property
from . import owner
from . import tag
from . import sale_order_inherit
from . import client
from . import building
from . import property_history
from . import account_move_inherit
